// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://daeljnzfaslarflfxeqj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRhZWxqbnpmYXNsYXJmbGZ4ZXFqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ1NTIzMTgsImV4cCI6MjA2MDEyODMxOH0.RQWgPa3nw3C8ph1GklaWy85i-J5HJQbmy5hjCW9kc5c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);